apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: result
    - podSelector:
        matchLabels:
          app: worker
    ports:
    - protocol: TCP
      port: 5432
