---

- name: VOTING APP NAMESPACE | Manage NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: votings
        namespace: "{{ app_namespace }}"
      spec:
        podSelector: {}
        policyTypes:
        - Ingress
        - Egress
        egress:
          - {}
