---

- name: VOTING APP REDIS | Manage NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: redis
        namespace: "{{ app_namespace }}"
      spec:
        podSelector:
          matchLabels:
            name: redis
        policyTypes:
        - Ingress
        ingress:
        - from:
          - podSelector:
              matchLabels:
                name: vote
          - podSelector:
              matchLabels:
                name: worker
          ports:
          - protocol: TCP
            port: 6379
