---

- name: VOTING APP REDIS | Manage Secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      type: Opaque
      data:
        redis-password: "{{ item.password | b64encode }}"
  with_items: "{{ redis_secret }}"
