---

- name: VOTING APP REDIS | Manage Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        ports:
        - name: "{{ item.name }}"
          port: 6379 # "{{ item.port }}"
          protocol: "{{ item.protocol }}"
          targetPort: 6379 # "{{ item.targetPort }}"
        selector:
          name: "{{ item.name }}"
        type: "{{ item.type }}"
  with_items: "{{ redis_services }}"
