apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: db
  namespace: voting-app-prd
type: Opaque
data:
  database-name: dm90aW5n
  database-password: azJuRE4yb1g=
  database-user: dm90aW5n
