apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: result
  namespace: voting-app-prd
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'result:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /sources/result
    git:
      ref: master
      uri: 'http://gitlab.lq.ca.treeptik.cloud/developers/voting-app.git'
    sourceSecret:
      name: gitlab-result
    type: Git
  strategy:
    dockerStrategy:
      env:
        - name: DB_SERVICE_NAME
          value: db
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: db
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: db
        - name: PORT
          value: '8080'
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: "GitLab"
    gitlab:
      secretReference:
        name: "gitlab-result"
  - type: "ConfigChange"
