apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  ports:
    - name: {{ template "fullname" . }}
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: {{ template "fullname" . }}
  type: ClusterIP
