---

- name: VOTING APP PROJECT | Manage LimitRange
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: voting
        namespace: "{{ app_namespace }}"
      spec:
        limits:
          - type: "Pod"
            max:
              cpu: "2"
              memory: "1Gi"
            min:
              cpu: "200m"
              memory: "6Mi"
          - type: "Container"
            max:
              cpu: "3"
              memory: "2Gi"
            min:
              cpu: "100m"
              memory: "4Mi"
            default:
              cpu: "500m"
              memory: "512Mi"
            defaultRequest:
              cpu: "200m"
              memory: "256Mi"
            maxLimitRequestRatio:
              cpu: "10"
