---

- name: VOTING APP PROJECT | Manage Project
  import_tasks: project.yml

- name: VOTING APP PROJECT | Manage Limit Range
  import_tasks: limitRange.yml
  when: app_state == 'present'

- name: VOTING APP PROJECT | Manage Network Policy
  import_tasks: networkPolicy.yml
  when: app_state == 'present'

- name: VOTING APP PROJECT | Manage Resource Quotas
  import_tasks: resourceQuota.yml
  when: app_state == 'present'

- name: VOTING APP PROJECT | Manage Secret
  import_tasks: secret.yml
  when: app_state == 'present'
