---

  - name: VOTING APP PROJECT | Manage Secret
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ item.name }}"
          namespace: "{{ app_namespace }}"
        type: "{{ item.type }}"
        data:
          password: "{{ item.password| b64encode }}"
          username: "{{ item.username | b64encode }}"
    with_items: "{{ project_secret }}"
