apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Values.image.tag | quote }}
data:
  option_a: {{ .Values.env.option_a | default ("KUBERNETES") | quote }}
  option_b: {{ .Values.env.option_b | default ("SWARM") | quote }}
