---

- name: VOTING APP WORKER | Manage Deployment
  k8s:
    state: present
    definition:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      metadata:
        name: "{{ worker_service_name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        revisionHistoryLimit: 5
        selector:
          name: "{{ worker_service_name }}"
        strategy:
          activeDeadlineSeconds: 21600
          rollingParams:
            intervalSeconds: 1
            maxSurge: 25%
            maxUnavailable: 25%
            timeoutSeconds: 600
            updatePeriodSeconds: 1
          type: Rolling
        template:
          metadata:
            labels:
              name: "{{ worker_service_name }}"
          spec:
            containers:
              - image: docker-registry.default.svc:5000/{{ app_namespace }}/worker
                imagePullPolicy: IfNotPresent
                name: "{{ worker_service_name }}"
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                resources:
                  requests:
                    cpu: 500m
                    memory: 512Mi
                  limits:
                    cpu: 1
                    memory: 1Gi
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
        triggers:
          - imageChangeParams:
              automatic: true
              containerNames:
                - "{{ worker_service_name }}"
              from:
                kind: ImageStreamTag
                name: 'worker:{{ app_version }}'
                namespace: "{{ app_namespace }}"
            type: ImageChange
          - type: ConfigChange
