---

- name: VOTING APP WORKER | Manage Secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      type: "{{ item.type }}"
      data:
        WebHookSecretKey: "{{ item.WebHookSecretKey | b64encode }}"
  with_items: "{{ worker_secret }}"
