---

###
# VOTING APP - DATABASE
###

# Global
database_service_name: db

# Service
database_services:
  - name: "{{ database_service_name }}"
    port: 5432
    protocol: TCP
    targetPort: 5432
    type: ClusterIP

# Volume
database_volumes:
  - name: "{{ database_service_name }}"
    size: 10Gi
    storageClass: gp2

# Secret
database_secret:
  - name: "{{ database_service_name }}"
    database: voting
    username: voting
    password: k2nDN2oX
