---

- name: VOTING APP REDIS | Manage Volume persistency
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: "{{ item.size }}"
        storageClassName: "{{ item.storageClass }}"
  with_items: "{{ redis_volumes }}"
