apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  ports:
    - name: 8080-tcp
      nodePort: 31000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: {{ template "fullname" . }}
  type: NodePort
