apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: voting-app-prd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
