apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: result
  namespace: voting-app-prd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
