apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: worker
  namespace: voting-app-prd
spec:
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
