apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "fullname" . }}-default-memory
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Release.Version | quote }}
spec:
  limits:
    - default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "fullname" . }}-max-memory
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Release.Version | quote }}
spec:
  limits:
    - max:
        memory: 1Gi
      defaultRequest:
        memory: 512Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "fullname" . }}-default-cpu
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Release.Version | quote }}
spec:
  limits:
    - default:
        cpu: 1
      defaultRequest:
        cpu: 0.2
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "fullname" . }}-maxcpu
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Release.Version | quote }}
spec:
  limits:
    - max:
        cpu: 2
      defaultRequest:
        cpu: 1
      type: Container
