---

- name: VOTING APP DATABASE | Manage Secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      type: Opaque
      data:
        database-name: "{{ item.database | b64encode }}"
        database-user: "{{ item.username | b64encode }}"
        database-password: "{{ item.password | b64encode }}"
  with_items: "{{ database_secret }}"
