apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  cpuUtilization:
    targetPercentage: 80
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    kind: DeploymentConfig
    name: {{ template "fullname" . }}
    apiVersion: apps/v1
