apiVersion: v1
kind: Secret
metadata:
  name: gitlab-{{ template "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
type: Opaque
data:
  WebHookSecretKey: {{ .Values.gitlab.password | b64enc }}
