---

- name: VOTING APP VOTE | Manage DeploymentConfig
  k8s:
    state: present
    definition:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      metadata:
        name: "{{ vote_service_name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        revisionHistoryLimit: 5
        selector:
          name: "{{ vote_service_name }}"
        strategy:
          activeDeadlineSeconds: 21600
          rollingParams:
            intervalSeconds: 1
            maxSurge: 25%
            maxUnavailable: 25%
            timeoutSeconds: 600
            updatePeriodSeconds: 1
          type: Rolling
        template:
          metadata:
            labels:
              name: "{{ vote_service_name }}"
          spec:
            affinity:
              podAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: name
                      operator: In
                      values:
                      - redis
                  topologyKey: "kubernetes.io/hostname"
            containers:
              - image: docker-registry.default.svc:5000/{{ app_namespace }}/vote
                imagePullPolicy: IfNotPresent
                name: "{{ vote_service_name }}"
                ports:
                  - containerPort: 8080
                    protocol: TCP
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
        triggers:
          - imageChangeParams:
              automatic: true
              containerNames:
                - "{{ vote_service_name }}"
              from:
                kind: ImageStreamTag
                name: 'vote:{{ app_version }}'
                namespace: "{{ app_namespace }}"
            type: ImageChange
          - type: ConfigChange
