---

- name: VOTING APP VOTE | Manage Image Stream
  k8s:
    state: present
    definition:
      apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
        name: vote
        namespace: "{{ app_namespace }}"
      spec:
        lookupPolicy:
          local: false
